feat(instrumentation): add shutdown hook
i-am-bee/bee-api pull request #142
Opened 2024-12-19 09:53 UTC by Tomas2D

2024-12-20 11:10 UTC, GALLLASMILAN reviewed
We should extract the function that calls the `forcePush` methods and call it in these hooks:
- `beforeExit`
- `exit`
- `uncaughtException`

2024-12-20 13:04 UTC, Tomas2D commented
- `exit` does not wait for async callback
-  if one uses `uncaughtException` it gets triggered before `beforeExit` so there is no need for doing so

2025-01-02 06:36 UTC, pilartomas requested changes

2025-01-02 06:36 UTC, pilartomas commented on src/opentelemetry.ts
> +  );
This should be removed as it is most likely unnecessary, call to `shutdown` appears to handle this exact thing, e.g. here for the traces https://github.com/open-telemetry/opentelemetry-js/blob/90afa2850c0690f7a18ecc511c04927a3183490b/packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts#L108.

2025-01-02 06:36 UTC, pilartomas commented on src/opentelemetry.ts
> +process.on('beforeExit', async () => {
We're using terminus to ensure shutdown is made on INT signal. Hooking onto `beforeExit` and awaiting shutdown can override that ,which is not what we'd want. However, I think we can live with it in this instance given the import limitations on this module.

2025-01-02 10:43 UTC, Tomas2D commented on src/opentelemetry.ts
> +  );
We need to do it manually; otherwise, I would not raise this PR.

2025-01-02 10:44 UTC, Tomas2D commented on src/opentelemetry.ts
> +process.on('beforeExit', async () => {
We can't hook to terminus as this script runs before the "application code." Using the `beforeExit` event is just fine because it runs immediately before the termination.

2025-01-02 10:51 UTC, pilartomas commented on src/opentelemetry.ts
> +  );
The important thing in this PR seems to be the shutdown call. Have you tested the code with just that?

2025-01-02 10:53 UTC, pilartomas commented on src/opentelemetry.ts
> +process.on('beforeExit', async () => {
Problem is that it can stop the termination from happening if sdk shutdown hangs, that is after terminus calls exit, correct?

It is not a blocker as stated above, solution would likely be quite hacky.

2025-01-02 11:00 UTC, Tomas2D commented on src/opentelemetry.ts
> +process.on('beforeExit', async () => {
Yes, this can happen, but should not, I can add an timeout.

2025-01-02 12:07 UTC, pilartomas commented on src/opentelemetry.ts
> +process.on('beforeExit', async () => {
Good idea, something of sorts  `await Promise.race([shutdown(), setTimeout(5000)]`

2025-01-03 08:02 UTC, GALLLASMILAN approved these changes

2025-01-03 08:27 UTC, Tomas2D commented on src/opentelemetry.ts
> +  );
We need to call `forceFlush` on all classes, and the problem is that not all of them implement this shutdown functionality as mentioned in `BatchSpanProcesssorBase`.

2025-01-03 09:24 UTC, pilartomas commented on src/opentelemetry.ts
> +  );
Which ones are problematic? We shouldn't implement a patch around shutdown without pinpointing the bug in the library.

2025-01-03 17:08 UTC, Tomas2D commented on src/opentelemetry.ts
> +  );
It seems it is not needed anymore.

2025-01-06 07:59 UTC, merged