feat(deps): remove langchain dependency
i-am-bee/bee-api pull request #80
Opened 2024-11-19 09:46 UTC by Tomas2D

Ref: #28

2024-11-19 10:51 UTC, pilartomas reviewed
I can still see lanchain and langsmith inside the lockfile, it is likely not removed.

2024-11-19 18:07 UTC, Tomas2D commented on src/files/extraction/helpers.ts
> +        separators: ['\n\n', '\n', ' ', '']
same behaviour

2024-11-20 08:22 UTC, pilartomas requested changes
Code looks good but langchain still gets installed via `pnpm install`

2024-11-20 10:37 UTC, Tomas2D commented
Yes, this seems to be a problem of `pnpm`. Fixed via `.npmrc`.

2024-11-20 12:25 UTC, pilartomas approved these changes

2024-11-20 12:38 UTC, merged